# Generated by Django 5.1.4 on 2026-03-10 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_type', models.CharField(choices=[('food_order', 'Food Order'), ('courier', 'Courier'), ('document', 'Document'), ('other', 'Other')], default='food_order', max_length=20)),
                ('status', models.CharField(choices=[('expected', 'Expected'), ('arrived', 'Arrived'), ('delivered', 'Delivered'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='expected', max_length=20)),
                ('platform_name', models.CharField(blank=True, help_text='e.g. Swiggy, Zomato, Amazon', max_length=100)),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('delivery_person_name', models.CharField(blank=True, max_length=255)),
                ('delivery_person_phone', models.CharField(blank=True, max_length=20)),
                ('expected_at', models.DateTimeField(blank=True, null=True)),
                ('otp_code', models.CharField(blank=True, max_length=6)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='companies.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='companies.employee')),
            ],
            options={
                'verbose_name_plural': 'deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
