# Generated by Django 5.1.4 on 2026-03-10 09:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_name', models.CharField(max_length=255)),
                ('visitor_phone', models.CharField(max_length=20)),
                ('visitor_email', models.EmailField(blank=True, max_length=254)),
                ('visitor_company', models.CharField(blank=True, max_length=255)),
                ('id_type', models.CharField(blank=True, max_length=50)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visitor_photos/')),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('purpose', models.TextField(blank=True)),
                ('pass_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('pass_type', models.CharField(choices=[('pre_approved', 'Pre-Approved'), ('walk_in', 'Walk-In'), ('recurring', 'Recurring')], default='pre_approved', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('expired', 'Expired'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_passes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_passes', to=settings.AUTH_USER_MODEL)),
                ('host_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_passes', to='companies.company')),
                ('host_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_passes', to='companies.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
